server:
  port: 8201

spring:
  application:
    name: Eden-Server-System
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  autoconfigure:
    # common模块里引入了mybatis-plus-boot-starter，该starter包含数据库自动装配配置，而server-system模块并没有配置数据库
    # 所以我们需要在它们的配置文件application.yml里添加如下配置来关闭数据库自动装配:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  instance:
    # 向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。表明当前服务没有宕机；
    lease-renewal-interval-in-seconds: 20
  client:
    # 将当前服务注册到Eureka服务端
    register-with-eureka: true
    # 从Eureka 服务端获取注册的服务信息
    fetch-registry: true
    # 新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    instance-info-replication-interval-seconds: 30
    # 默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可；
    registry-fetch-interval-seconds: 3
    serviceUrl:
      # 指定Eureka服务端地址
      defaultZone: http://eden:123456@localhost:8081/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # user-info-uri路径为http://localhost:8301/auth/user，通过微服务网关，该请求将被转发到http://localhost:8101/user。该配置的作用主要有两个：
      #1.到认证服务器里校验当前请求头中的令牌是否为合法的令牌；
      #2.通过当前令牌获取对应的用户信息。
      user-info-uri: http://localhost:8301/auth/user