server:
  port: 8101

spring:
  application:
    name: Eden-Auth
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: EdenHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/eden?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

mybatis-plus:
  # 指定别名扫描路径，该路径下的实体类将自动配置别名，默认为类名首字母小写。配置别名后，便可以直接在MyBatis XML文件里使用了；
  type-aliases-package: com.peijia.**.domain
  # 指定MyBatis XML文件路径；
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 指定为null，否则再插入空值时会报“无效的列类型”错误；
    jdbc-type-for-null: null
  global-config:
    # 设置为false关闭MyBatis Plus Banner打印。
    banner: false

eureka:
  instance:
    # 向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。表明当前服务没有宕机；
    lease-renewal-interval-in-seconds: 20
  client:
    # 将当前服务注册到Eureka服务端
    register-with-eureka: true
    # 从Eureka 服务端获取注册的服务信息
    fetch-registry: true
    # 新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    instance-info-replication-interval-seconds: 30
    # 默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可；
    registry-fetch-interval-seconds: 3
    serviceUrl:
      # 指定Eureka服务端地址
      defaultZone: http://eden:123456@localhost:8081/register/eureka/